### PR TITLE
add prototype of subscribe and span api

### PR DESCRIPTION
**Pull request by brettlangdon**
This PR adds two prototype concepts, event subscriptions and a Span api.

## Subscriptions
When you add an audit hook, that hook will get called for every single event that occurs. If you only want to listen on some events you have to include an if check and early exit from your hook.

This addition adds a `subscribe(event, hook)` function which will register a single audit hook that when called will only call hooks subscribed to specific events.

```python
import sysaudit

def test_hook(event, args):
    if event != "test":
        print("skipping", event)
        return

    print("test_hook", args)

def test_subscribe(args):
    print("test_subscribe", args)

sysaudit.addaudithook(test_hook)
sysaudit.subscribe("test", test_subscribe)

sysaudit.audit("test", 1, 2, 3)
# test_hook (1, 2, 3)
# test_subscribe (1, 2, 3)

sysaudit.audit("another_event")
# skipping another_event
```

## Span api
This PR also adds in a `Span` construct to make it easier to implement start/end lifetime events.

```python
import wsgiref.util

import sysaudit


def http_request_hook(args):
    # `args` will always be `(sysaudit.Span.Message(), )`
    (msg,) = args

    # Note: We added environ to `Span.data` so it will persist through all events
    request_uri = wsgiref.util.request_uri(msg.span.data["environ"])

    if msg.type == "start":
        print(f"start\t{msg.span.id}\t{request_uri}")
    elif msg.type == "end":
        print(f"end\t{msg.span.id}\t{request_uri}")
    elif msg.type == "annotate":
        print(f"data\t{msg.span.id}\t{msg.data}")


sysaudit.subscribe("http.request", http_request_hook)


def application(environ, start_response):
    with sysaudit.Span("http.request", dict(environ=environ)) as span:
        status = "200 OK"
        headers = [("Content-Type", "text/html")]

        # Send a message with the response information
        span.annotate(dict(status=status, headers=headers))
        start_response(status, headers)

        return [b"Hello World"]


if __name__ == "__main__":
    from wsgiref.simple_server import make_server

    with make_server("127.0.0.1", 8000, application) as httpd:
        httpd.serve_forever()
```

```
$ python run.py
start	4524635776	http://localhost:8000/
data	4524635776	{'status': '200 OK', 'headers': [('Content-Type', 'text/html')]}
end	4524635776	http://localhost:8000/
127.0.0.1 - - [14/Feb/2021 09:43:57] "GET / HTTP/1.1" 200 11
```

### CODE REVIEW

**Comment by brettlangdon** [comment]
cc @Kyle-Verhoog

**Comment by brettlangdon** [comment]
@Kyle-Verhoog I tried to see what this would look like in Flask. This probably isn't the best implementation inside of Flask, but just wanted to see what this could look like for instrumentation side.

```diff
diff --git a/src/flask/app.py b/src/flask/app.py
index 496732ec..e05ad1eb 100644
--- a/src/flask/app.py
+++ b/src/flask/app.py
@@ -5,6 +5,7 @@ from datetime import timedelta
 from itertools import chain
 from threading import Lock
 
+import sysaudit
 from werkzeug.datastructures import Headers
 from werkzeug.datastructures import ImmutableDict
 from werkzeug.exceptions import BadRequest
@@ -2005,9 +2006,11 @@ class Flask(Scaffold):
         """
         ctx = self.request_context(environ)
         error = None
+        span = sysaudit.Span("flask.request", data=ctx)
         try:
             try:
                 ctx.push()
+                span.start()
                 response = self.full_dispatch_request()
             except Exception as e:
                 error = e
@@ -2015,11 +2018,14 @@ class Flask(Scaffold):
             except:  # noqa: B001
                 error = sys.exc_info()[1]
                 raise
+
+            span.message("response", response)
             return response(environ, start_response)
         finally:
             if self.should_ignore_error(error):
                 error = None
             ctx.auto_pop(error)
+            span.end(dict(error=error))
 
     def __call__(self, environ, start_response):
         """The WSGI server calls the Flask application object as the
```


```python
import ddtrace
import flask
import sysaudit


spans = dict()


@sysaudit.subscribe("flask.request")
def flask_request_hook(args):
    (msg,) = args

    if msg.type == "start":
        ctx = msg.span.data
        span = ddtrace.tracer.trace(msg.span.name, resource=ctx.request.url_rule.rule)
        span.set_tag("http.url", ctx.request.url)
        spans[msg.span.id] = span
    elif msg.type == "end":
        span = spans.get(msg.span.id)
        if not span:
            return

        error = msg.data["error"]
        if error:
            span.set_exc_info(type(error), error, error.__traceback__)
        span.finish()
        del spans[msg.span.id]
    elif msg.type == "response":
        span = spans.get(msg.span.id)
        if not span:
            return

        resp = msg.data
        span.set_tag("http.status_code", resp.status_code)


app = flask.Flask(__name__)


@app.route("/")
def index():
    return "Hello, world!"


@app.route("/error")
def error():
    raise RuntimeError("OH NO!")


if __name__ == "__main__":
    app.run()
```

**Review by Kyle-Verhoog — COMMENTED** [review]
Nice!

I'm not 100% about needing to register on every single span type event. Do we lose anything by submitting just `span.start`, `span.end` and `span.annotate` events or even just `span` events? Is the idea here that a `flask.request` event could be used for other applications (besides tracing)?

One technical concern might be that adding so many events might result in a pretty large set of events that each audithook will be called with.

**Comment by brettlangdon** [comment]
> I'm not 100% about needing to register on every single span type event. Do we lose anything by submitting just `span.start`, `span.end` and `span.annotate` events or even just `span` events? 

I am definitely open to suggestions on the API. It is definitely important that every span event has, some indication of source (e.g. "flask request"), the type of event ("start", "end", "annotate"), along with some caller defined data (e.g. `flask.request`, "error", etc).

Whether that gets emitted under different `sys.audit` event names or under a single one doesn't matter too much to me.

Ignoring the "subscription" helpers added here, we should try to make sure that whatever we design for how span events are emitted roughly follows the pattern/guidelines set out by PEP578: https://www.python.org/dev/peps/pep-0578/#suggested-audit-hook-locations

That is, an event is a contract, saying, this event name will have these specific parameters. So the idea I was going for was, a `flask.request` event will always have a `SpanMessage` argument only, which the `SpanMessage` has it's own API/contract of an event name and data, etc.

We could go a few different directions with it, like `sys.audit("flask.request.start", span_id, request)`, `sys.audit("flask.request.end", span_id, error)`, `sys.audit("flask.request.response", span_id, response)`... or anything really. I am open to ideas here.

> Is the idea here that a `flask.request` event could be used for other applications (besides tracing)?

Yeah, we don't want to design something that is only useful for tracing. Since we are building off of `sys.audit` which is meant as a general purpose "hook" system. Library maintainers should instrument their libraries with `sys.audit` knowing that it might be used for security auditing (maybe even so far as "reject this request because it looks like a bot"), or for tracing, or for anything else really.

> One technical concern might be that adding so many events might result in a pretty large set of events that each audithook will be called with.

Yes, and have to remember that every hook registered will be called with all the system events as well.

```python
import sys

def hook(event, args):
    print(event, args)

sys.addaudithook(hook)

import typing
```

The performance impact is pretty low (from info provided in the PEP and some local testing), you'd probably need to register 100 audit hook listeners to really notice a performance impact. I think someone having somewhere between 1 and 10 audit hook listeners seems plausible. It really depends on whether vendors go for a single listener model or one per-event. I think the latter is the better approach.

That is:

```python
def flask_hook(event, args):
    if event != "flask.request":
        return

    # do something with args here

# vs

def vendor_hook(event, args):
    if event == "flask.request":
        return handle_flask_event(*args)
```

The latter should have a performance benefit from being able to avoid a bunch of if comparisons and unnecessary function calls (calling every hook every time vs choosing which one to call), but probably mostly negligible unless you have a _ton_ of listeners.

**Pull request closed without merging**
